### ISSUE TITLE
Items not being displayed

### ISSUE THREAD

**Issue by whatmicha** [UrukBartas/Game#36]
Hi,

i have this issue on my laptop with chrome - it works perfectly fine on mobile - couldn't check any other browser so far.
It  might be related to me and not to your game but wanted to share this 

![image](https://github.com/UrukBartas/Game/assets/110422993/e45cc90d-5ab8-4750-aa62-4561be93260f)

**Comment by tihomir22** [comment]
Hey @whatmicha, we already investigated this issue and it is related to our IPFS, as it is not dependant on us, we can't ensure that it won't happen as issues could appear again. For that reason, we will be looking for a solution to replace this provider and give better user experience 👍🏻 

At least for now seems like it got fixed, so I will close the Issue.

Thank you for reporting this!
